### ISSUE TITLE
Use 2017 until there are actually 2018 photos

### ISSUE THREAD

**Issue by balghane** [frc1418/FRCNewTab#33]
Currently, no teams have photos because it's looking for 2018 photos, which obviously no team has yet. Have it look for 2017 photos until comp season begins?

**Comment by ErikBoesen** [comment]
That seems like a reasonable idea.

**Comment by ianzullo** [comment]
Just to clarify, what are you seeing when you open a new tab? Could you send a screenshot of the issue you are experiencing?

**Comment by balghane** [comment]
As of now, since there are no 2018 photos, the new tab will always have a default photo like this one 
![image](https://user-images.githubusercontent.com/5142966/34796936-446001e6-f625-11e7-9c4c-471761c12955.png)

It'd be nice if it showed 2017 photos until there are actually 2018 photos to see.

**Comment by ErikBoesen** [comment]
@ianzullo The photos which do appear are placeholders, not actual photos from The Blue Alliance.
