### ISSUE TITLE
Many teams' pictures aren't showing

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/FRCNewTab#38]
254, for example, is shown as having no picture. Don't know if this has something to do with the current month...

**Comment by AndrewLester** [comment]
For future reference: Has this been tested on chrome which isn't on our macbooks?

**Comment by ErikBoesen** [comment]
@AndrewLester I've tested it on Firefox on my MacBook. Never on any other device, but I can't imagine there being much difference...

**Comment by AndrewLester** [comment]
Just wanted to make sure it wasn't just chrome. (I can't load imgur images because of school's block)

**Comment by ErikBoesen** [comment]
The school is blocking Imgur?

_Imgur?_

**Comment by ianzullo** [comment]
its a funny meme website people will use it to procrastinate.

**Comment by ErikBoesen** [comment]
True. It's occasionally used for image hosting, though. _For example_

**Comment by ianzullo** [comment]
if you've only tested it on your macbook then its probably a problem with imgur blocking, which is why only some work (ones not hosted on imgur.) someone should test it on a non-macbook
