### ISSUE TITLE
bg10 not from Georgia

### ISSUE THREAD

**Issue by Eiim** [frc1418/FRCNewTab#47]
I was looking closely at the backgrounds and noticed that one of them, specifically # 10, was actually [Quals 188 from MSC](https://www.thebluealliance.com/match/2016micmp_qm188). I know that the Settings page says some backgrounds are used from the Georgia Flikr page with permission, but I couldn't find any Michigan teams from 2016 there. Don't know if this just came from somewhere else with permission, just thought I'd check to make sure!

**Comment by ErikBoesen** [comment]
Gotta be honest, it's been a long time since I put those photos in. I don't remember taking photos from anywhere else. If this concerns you feel free to make a PR and remove the offending background. If you want to add some more up-to-date images (i.e. not from Stronghold) that'd be great too.

**Comment by ErikBoesen** [comment]
Closing and replacing with #48
