### ISSUE TITLE
BWNT pushed to Firefox

### ISSUE THREAD

**Issue by tweirtx** [frc1418/FRCNewTab#49]
I'm a user of FRC New Tab. Recently, it seems like FRC New Tab has changed to erikboesen/BWNT on Firefox. Can this be changed back please?

**Comment by ErikBoesen** [comment]
Good lord... I'm an idiot. Will fix this right now.

**Comment by ErikBoesen** [comment]
Pushed a new version. Sorry about that and thanks for letting me know.

**Comment by tweirtx** [comment]
No problem, thanks for getting it fixed so quickly!

**Comment by tweirtx** [comment]
I think the version number has to be higher than the "old one" which is showing as 2.1.3 (BWNT)

**Comment by ErikBoesen** [comment]
Fixed.
